# Generated by Django 5.1.4 on 2024-12-08 15:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_statusmodel_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='bikemodel',
            constraint=models.UniqueConstraint(fields=('name', 'model_number'), name='unique_bike_model'),
        ),
    ]
