# Generated by Django 4.2.17 on 2024-12-12 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_bikemodel_unique_bike_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryorder',
            name='status',
            field=models.ForeignKey(default='PENDING', on_delete=django.db.models.deletion.CASCADE, to='orders.statusmodel'),
        ),
    ]
